series: Bufferless Rendering
title: Rendering without Vertex Data
author:
  name: Joshua Alway
  email: 
  github: https://github.com/IGME-RIT
description: Render geometry using nothing but an index buffer.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Intro to Shaders